version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cmanager-php:latest
    container_name: cmanager-app
    ports:
      - "9012:9012"
    environment:
      APP_ENV: local
    depends_on:
      - postgres
    restart: always
    extra_hosts:
      - "host.docker.internal:172.27.0.1"
    develop:
      watch:
      - action: sync
        path: .
        target: /app
        ignore:
          - vendor/
          - .git/
          - docker-compose.yml
          - Dockerfile
          - README.md
          - bootstrap/cache/
          - storage/

  postgres:
    image: postgres:16-alpine
    container_name: cmanager-postgres
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: tvshow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
